#!/bin/bash
SESSION=`basename $PWD`

TERM="screen-256color"
tmux -2 new-session -d -s $SESSION

tmux rename-window -t $SESSION:1 vim
# tmux send-keys -t $SESSION:1 'vifm' C-m
tmux send-keys 'vifm' C-m
tmux split-window -h
tmux send-keys 'vim' C-m
tmux resize-pane -L 40
tmux split-window -v
tmux resize-pane -D 30

tmux new-window -t $SESSION -a -n server

tmux select-window -t $SESSION:1
tmux select-pane -t 2
tmux -2 attach -t $SESSION
